### ISSUE TITLE
支持MKV格式的视频的裁剪吗

### ISSUE THREAD

**Issue by mrme2014** [iknow4/Android-Video-Trimmer#11]
支持MKV格式的视频的裁剪吗

**Comment by iknow4** [comment]
需要使用mkv视频进行一下测试，该项目还没有测试过。

**Comment by iknow4** [comment]
@mrme2014 你有mkv的视频么，有的话可以提供一下。

**Comment by iknow4** [comment]
@mrme2014  VideoView不支持MKV格式文件的播放，所以不支持MKV格式的视频的裁剪
