### ISSUE TITLE
下面的缩略图显示不出来

### ISSUE THREAD

**Issue by LCJustin** [iknow4/Android-Video-Trimmer#15]
视频裁剪3分钟的视频，下面的缩略图出不来

**Comment by iknow4** [comment]
@LCJustin 具体什么现象？是应用死掉了吗？查看一下logcat是不是有异常抛出了

**Comment by LCJustin** [comment]
我之前用的版本还是不错的，现在新的好像改动有点大？能否请教一下了，952923539，这是我的QQ

**Comment by iknow4** [comment]
@LCJustin 之前的版本有些UI上bug一直比较难解决，新版换成RecycleView来显示视频帧。

**Comment by LCJustin** [comment]
我一个3分钟的视频进行裁剪，拖动下面的裁剪片段，滑到一半就没有缩略图了，黑的，打印信息：
MediaMetadataRetrieverJNI: getFrameAtTime: create Bitmap failed!
06-05 18:00:23.778 19651-19697/com.iknow.android W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
06-05 18:00:23.778 19651-19697/com.iknow.android W/System.err:     at com.iknow.android.utils.TrimVideoUtil$2.execute(TrimVideoUtil.java:93)
06-05 18:00:23.778 19651-19697/com.iknow.android W/System.err:     at iknow.android.utils.thread.BackgroundExecutor$Task.run(BackgroundExecutor.java:212)
06-05 18:00:23.778 19651-19697/com.iknow.android W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
06-05 18:00:23.778 19651-19697/com.iknow.android W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
06-05 18:00:23.778 19651-19697/com.iknow.android W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
06-05 18:00:23.778 19651-19697/com.iknow.android W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
06-05 18:00:23.778 19651-19697/com.iknow.android W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
06-05 18:00:23.778 19651-19697/com.iknow.android W/System.err:     at java.lang.Thread.run(Thread.java:762)
