### ISSUE TITLE
android 模拟器运行ffmpeg压缩，报错

### ISSUE THREAD

**Issue by zhaoweijing2003** [iknow4/Android-Video-Trimmer#17]
CANNOT LINK EXECUTABLE "/data/user/0/com.iknow.android/files/ffmpeg": /data/data/com.iknow.android/files/ffmpeg: has text relocations
![image](https://user-images.githubusercontent.com/5343500/41648870-a9a7bc50-74ac-11e8-9d32-2ab69e86a846.png)

**Comment by iknow4** [comment]
@zhaoweijing2003  建议使用真机。
