### ISSUE TITLE
Missing Classes

### ISSUE THREAD

**Issue by symphonyrecords** [iknow4/Android-Video-Trimmer#18]
Your project is missing some classes like :  _**iknow.android.utils.DeviceUtil**_  | _**UnitConverter**_ | _**SimpleCallback**_ |  _**SingleCallback**_  ...

**Comment by iknow4** [comment]
@symphonyrecords  
please add implementation 'com.github.iknow4:android-utils-sdk:1.1.2'  in  your app/build.gradle file
