### ISSUE TITLE
长视频裁剪出来的时间不是想要的时间

### ISSUE THREAD

**Issue by gyymz1993** [iknow4/Android-Video-Trimmer#19]
长视频裁剪出来的时间不是想要的时间

**Comment by iknow4** [comment]
@gyymz1993 裁剪后的视频时间与选择的时间段不符么？你的视频长度是多少？

**Comment by gyymz1993** [comment]
![image](https://user-images.githubusercontent.com/9989409/42997897-e6de8544-8c4a-11e8-8a1e-36add6198f74.png)

选择一个十秒的视频   我菜三秒  结果出来的是6秒

**Comment by gyymz1993** [comment]
![image](https://user-images.githubusercontent.com/9989409/42998110-a56b84a8-8c4b-11e8-9071-1cfadc89f7f4.png)

**Comment by iknow4** [comment]
@gyymz1993  你在文件管理器中，Storage->data->com.iknow.android->Cache目录下面,查看最新裁剪出来的视频compress.mp4
看看是多少秒

**Comment by gyymz1993** [comment]
![image](https://user-images.githubusercontent.com/9989409/42998263-252644c6-8c4c-11e8-87e3-4f53460b75b0.png)
裁剪出来的是6秒

**Comment by gyymz1993** [comment]
而且我发现一个问题  你如果改变endTime问题不大  不改变startTime的话就会出现这个问题

**Comment by gyymz1993** [comment]
会不会因为视频源  我选择的这个视频是我们加了滤镜处理后的视频

**Comment by iknow4** [comment]
你试试其他视频源么？

发自我的 iPhone

**Comment by gyymz1993** [comment]
我看了下 播放的时长只有三秒   实际显示时长为6秒   我看到有人提到这个问题   但我按照那样加命令就不能裁剪了  应该是什么样的命令呢

**Comment by gyymz1993** [comment]
而且没有失败的回调  可能会一直卡在剪切不动   没见走过异常的   如果裁剪不了就一直卡着

**Comment by gyymz1993** [comment]
https://pan.baidu.com/s/1y9SmnXO3KcaM8onImefcNQ

**Comment by gyymz1993** [comment]
这是裁剪的视频

**Comment by gyymz1993** [comment]
https://pan.baidu.com/s/1FN86sU5BXXlCoBffrDCGFQ  这个是十秒的原视频 
https://pan.baidu.com/s/1y9SmnXO3KcaM8onImefcNQ  这个是裁剪3秒后的出现的6秒的不正常视频

**Comment by iknow4** [comment]
好的，谢谢！

发自我的 iPhone

**Comment by 1242128273wangpeng** [comment]
我发现用ffmpeg命令行裁剪的视频长度不精准，我用ffmpeg在windows上运行命令裁剪视频，像-i -ss -t -to
 挪前挪后都试过，还很容易出现黑屏或者是卡帧的情况，但是一些成熟的app就没有这种情况，会不会是jni实现的呢?作者若解决 望告知一下

**Comment by iknow4** [comment]
@1242128273wangpeng 
你的这个问题是因为你的命令-ss -t -to 需要优化成-ss -t  -i 之后应该不会出现
黑屏或者是卡帧。但是裁剪视频不精准很可能与视频的关键帧有关系。

**Comment by gyymz1993** [comment]
我们的就是做小视频制作  剪切都需要很精确   你这个demo是以秒为单位裁剪  我们是以毫秒裁剪的

**Comment by gyymz1993** [comment]
而且这个demo有些问题   你退出后台再进的话下面的recycleview会重复     那个初始化的地方不能方式视频里面

**Comment by iknow4** [comment]
嗯，现在基本都是用秒做单位的

发自我的 iPhone

**Comment by gyymz1993** [comment]
我这个问题有解吗   用原生的裁剪对于那种加速的视频或者处理过的视频也会出现这种情况

**Comment by 1242128273wangpeng** [comment]
对，我试了重新编码，确实确实比之前的精确。
这篇文章有介绍：https://superuser.com/questions/499380/accurate-cutting-of-video-audio-with-ffmpeg

**Comment by gyymz1993** [comment]
具体怎么用呢

**Comment by gyymz1993** [comment]
String cmd = "-ss " + start + " -i " + inputFile + " -ss 0" + " -t " + duration + " -c copy -map 0 " + outputFile;
这个命令剪切出来的还可以  不过我在测试测试

**Comment by iknow4** [comment]
时间对么？

**Comment by gyymz1993** [comment]
有一定的误差  我还在查 
![image](https://user-images.githubusercontent.com/9989409/43069447-aca099ec-8e9f-11e8-9388-89311aa25bc9.png)
这是我切的以前那个视频  3秒时间切出来是2949

**Comment by gyymz1993** [comment]
大兄弟  虽然时间是对的  裁剪出来的视频是有问题的  还是有坑啊啊

**Comment by gyymz1993** [comment]
嗯  找到了一个国外的大神的命令解决了这个问题   那个seekbar是你写的吗  我现在还要在上面加左右移动事件

**Comment by iknow4** [comment]
嗯，你可以自己加的。
