### ISSUE TITLE
将时间精确到0.1秒为单位的裁剪

### ISSUE THREAD

**Issue by gyymz1993** [iknow4/Android-Video-Trimmer#21]
如果我将时间改为每次裁剪区域时间为60秒
  裁剪时间精确到毫秒的话 
发现拖动右边进度条的准确有问题  
不是很清楚这块的算法

![image](https://user-images.githubusercontent.com/9989409/43247881-a1ddf69e-90e8-11e8-84dd-3359b3b9e39b.png)
迫不得已自己加了没有完美的减去了一定的宽度，精确度提高了解决了我的问题 不过不知道是哪里造成的误差   左边的没有这个问题

**Comment by iknow4** [comment]
左右进度条拖动是会精确到毫秒的，但UI上只精确到秒，没有对毫秒做四舍五入。比如左边的进度条是5600ms，但具体会显示成5s

**Comment by gyymz1993** [comment]
我测试过了   如果以10秒为单位裁剪不会有问题   如果以60秒为单位的话  右边拖动就会调针

**Comment by iknow4** [comment]
那，现在是UI上的问题咯，裁剪命令ok了？

**Comment by gyymz1993** [comment]
裁剪的基本上没问题了  不过就我这边而言的话出现了另一个问题   我们裁剪压缩上传三部操作再一起   然后可能压缩过的视频在裁剪就会出现黑屏   如果没有压缩过的基本上没什么问题  我上面的命令基本上可以精确到毫秒的裁剪了
