### ISSUE TITLE
ffmpeg总感觉压缩时间太慢了，如果只需要用到压缩的话，推荐

### ISSUE THREAD

**Issue by tangpeng** [iknow4/Android-Video-Trimmer#28]
我推荐一个压缩更加快的，https://github.com/tangpeng/VideoCompressor   一个5分钟的视频，大小为646M 压缩时间3分钟

**Comment by yungelee** [comment]
> 我推荐一个压缩更加快的，https://github.com/tangpeng/VideoCompressor 一个5分钟的视频，大小为646M 压缩时间3分钟

这个是走硬编码吧？据说这个走MeidaCodec类的硬编会有不少兼容性问题，你们项目中是哟你个这个吗？
