### ISSUE TITLE
4.4系统版本RangeSeekBarView拖动左边和右边的托块之后无法绘制阴影遮盖，不知道是什么原因

### ISSUE THREAD

**Issue by huangjinhong** [iknow4/Android-Video-Trimmer#32]

**Comment by iknow4** [comment]
@huangjinhong 谢谢反馈，我这边看下是什么原因。

**Comment by huangjinhong** [comment]
@iknow4 知道是什么原因吗？我看代码，看不出什么原因

**Comment by iknow4** [comment]
@huangjinhong 我这边没有4.4的系统设备，需要用模拟器来观察下情况。

**Comment by huangjinhong** [comment]
@iknow4 我开始是怀疑是不是API过时的原因，换了也没效果

**Comment by huangjinhong** [comment]
@iknow4 我使用5.0的机型也会出现这个问题

**Comment by iknow4** [comment]
@huangjinhong  你跟踪一下那块绘制的逻辑看看

**Comment by iknow4** [comment]
@huangjinhong 
尴尬。居然跟硬件加速有关，那这个问题是比较难发现的。
