### ISSUE TITLE
怎么会把相册里面的图片的时长也裁剪了?

### ISSUE THREAD

**Issue by wangtao2855** [iknow4/Android-Video-Trimmer#35]

**Comment by iknow4** [comment]
不太懂你的意思，能截图看下或者能具体说下你的问题么？

**Comment by wangtao2855** [comment]
比如我选择了一个视频,视频长度为30秒,下一步就是裁剪视频了,我们固定最长10秒,他裁剪万10秒之后,我发现它相册的视频竟然也是10秒了,对 真的是这样

**Comment by wangtao2855** [comment]
> 不太懂你的意思，能截图看下或者能具体说下你的问题么？

比如我选择了一个视频,视频长度为30秒,下一步就是裁剪视频了,我们固定最长10秒,他裁剪万10秒之后,我发现它相册的视频竟然也是10秒了,对 真的是这样

**Comment by iknow4** [comment]
@wangtao2855  
裁剪后的视频是10秒，但是你原来30秒的视频不会有变化的，还是30秒。

**Comment by wangtao2855** [comment]
真的会有变化 您家我1141484506 我给您录屏

**Comment by iknow4** [comment]
@wangtao2855  你的意思是，30秒的视频也变成了10秒？

**Comment by wangtao2855** [comment]
对 那是相册上面时间还是显示30秒,你点击打开,让他播放 看他的进度时长,其实已经是10秒了
