### ISSUE TITLE
在小米5手机压缩出现压缩失败

### ISSUE THREAD

**Issue by lshAndroid** [iknow4/Android-Video-Trimmer#37]
小米手机5,Android 8.0,26.但是出现compress video failed

**Comment by iknow4** [comment]
只是压缩失败？程序有奔溃吗？

J.Chou  
发自我的 iPhone

**Comment by lshAndroid** [comment]
程序没有崩溃,
 VideoCompressor.compress(this, in, out, new VideoCompressListener() {
      @Override public void onSuccess(String message) {
        ToastUtil.longShow(VideoTrimmerActivity.this,"成功"+message);
      }

      @Override
      public void onFailure(String message) {
        ToastUtil.longShow(VideoTrimmerActivity.this, "失败"+message);
      }
回调onFauilure方法了

**Comment by iknow4** [comment]
@lshAndroid 
可以在VideoCompressor里查看下compress失败的具体信息。

**Comment by lshAndroid** [comment]
> @lshAndroid
> 可以在VideoCompressor里查看下compress失败的具体信息。
现在回调成功没问题了,懵逼,谢谢.可能是小米手机问题

**Comment by lshAndroid** [comment]
现在回调成功没问题了,懵逼,谢谢.可能是小米手机缓存问题
