### ISSUE TITLE
编译 缺少ActivityRecordingLayoutBinding

### ISSUE THREAD

**Issue by PawnLee** [iknow4/Android-Video-Trimmer#38]
Error:(7, 37) 错误: 找不到符号
符号:   类 ActivityRecordingLayoutBinding
位置: 程序包 com.iknow.android.databinding

**Comment by iknow4** [comment]
在build.gradle中开启 databinding

**Comment by PawnLee** [comment]
dataBinding {
        enabled = true
    }
默认是开启的

同时导入R文件也报错

**Comment by PawnLee** [comment]
```
dataBinding {
    enabled = true
}
```

默认是开启的


同时导入R文件也报错

**Comment by iknow4** [comment]
gradle 同步下。这个问题应该是你的工程没用同步好。

**Comment by PawnLee** [comment]
我这边看databinding包下没有ActivityRecordingLayoutBinding 文件。

注释后，可以在手机上运行

**Comment by iknow4** [comment]
你代码是最新的吗？

**Comment by PawnLee** [comment]
最新的
