### ISSUE TITLE
裁剪框不能拖到最后

### ISSUE THREAD

**Issue by xiemobiao** [iknow4/Android-Video-Trimmer#39]
例如一个视频有22秒，只能选择裁剪前面19s的内容，最后几秒裁剪框不能拖动到那里

**Comment by iknow4** [comment]
@xiemobiao 
你是不是从后台进前台出现的这样的问题？

**Comment by xiemobiao** [comment]
不是，直接打开就是这样的

**Comment by ITzhangyan** [comment]
@xiemobiao 请问你解决了么，确实有这个问题

**Comment by java-tangbing** [comment]
两个bug  1、  视频过长 显示不完整 少2秒或者3秒   2、页面不可见到可见 视频长度变长 （原因：videoPrepared 重新执行 startShootVideoThumbs方法导致list 增加 ）

解决：bug1 只要限制不能拖动就行 bug2 添加拦截   if(firstInit){
            startShootVideoThumbs(this, mSourceUri, mThumbsTotalCount, 0, mDuration);
            firstInit = false;
        }
