### ISSUE TITLE
Avi files with codec MjPEG throws FIle not found exception

### ISSUE THREAD

**Issue by rahulvyas** [iknow4/Android-Video-Trimmer#44]
Hi,

When I pick avi file encoded with MjPEG codec I am getting file not found exception in logs. Do you have any idea how to catch this exception or how to run the avi video ?

**Comment by iknow4** [comment]
I need to test with an avi file. Can you upload an avi video file here?

**Comment by rahulvyas** [comment]
Here you go
https://www.dropbox.com/s/iyo0pot2ryfyteq/PICT0021.AVI?dl=0

Download from dropbox to directly into your phone storage and then check.

**Comment by rahulvyas** [comment]
@iknow4 did you tested the AVI file ? You haven't replied anything and you closed the issue..

**Comment by iknow4** [comment]
> @iknow4 did you tested the AVI file ? You haven't replied anything and you closed the issue..

i have fix this issue.

**Comment by rahulvyas** [comment]
Have you merged this into master or any other branch with this fix included ?

**Comment by iknow4** [comment]
> Have

yeah, i hava merged to the master branch.

**Comment by iknow4** [comment]
> Have you merged this into master or any other branch with this fix included ?

yeah, i hava merged to the master branch.
