### ISSUE TITLE
Reset

### ISSUE THREAD

**Issue by 1appstudio** [iknow4/Android-Video-Trimmer#49]
I have implemented your code, It works great. But I need to refresh all the component once I changed the video. Here I changed VideoTrimmerview, recycle Adapter but cant refreshing RangeSeekBarView. Please help us.

**Comment by 1appstudio** [comment]
How can I reset the trimmer view on button click

**Comment by iknow4** [comment]
Can you tell me what problem you are encountering now, is there a screenshot or a related error log？

**Comment by 1appstudio** [comment]
I have three placeholders, I can add three videos, selecting each placeholder, respective VideoTrimmerView is loaded. Now each video has different seconds.

The trimmer view &  Adapter(Thumbnail & seconds) is not getting refreshed.

We are using the below code to load the videos into the VideoTrimmerview.
trimmerView.initVideoByURI(Uri.parse(selectedVideos.get(0).toString()))

**Comment by 1appstudio** [comment]
I have loaded one video into the Trimmerview, now I want to change the video and its Thumbnail adapter & RangeSeekbar without going back to the previous screen, how can I achieve it.

**Comment by iknow4** [comment]
when you loaded one video into the Trimmerview, and you want to change the video and its Thumbnail adapter & RangeSeekbar without going back to the previous screen. now, I understand that what you mean is you need a button on Trimmerview page to select other videos to load to the Trimmerview page, right?

**Comment by iknow4** [comment]
I suggest you can send a few pictures to explain your intentions, you know, a picture is worth a thousand words！

**Comment by 1appstudio** [comment]
> when you loaded one video into the Trimmerview, and you want to change the video and its Thumbnail adapter & RangeSeekbar without going back to the previous screen. now, I understand that what you mean is you need a button on Trimmerview page to select other videos to load to the Trimmerview page, right?

Yes exactly

**Comment by 1appstudio** [comment]
> when you loaded one video into the Trimmerview, and you want to change the video and its Thumbnail adapter & RangeSeekbar without going back to the previous screen. now, I understand that what you mean is you need a button on Trimmerview page to select other videos to load to the Trimmerview page, right?

Yes, this is what I want. Please help us to implement

**Comment by iknow4** [comment]
> > when you loaded one video into the Trimmerview, and you want to change the video and its Thumbnail adapter & RangeSeekbar without going back to the previous screen. now, I understand that what you mean is you need a button on Trimmerview page to select other videos to load to the Trimmerview page, right?
> 
> Yes, this is what I want. Please help us to implement

I don't know how to help you, I think this is a problem of page friendly design.

**Comment by 1appstudio** [comment]
Please find the preview of the player we are using https://www.dropbox.com/s/xmokrmpuxu99rcs/QueryImage.png?dl=0

Do you have any suggestion?

**Comment by iknow4** [comment]
> Please find the preview of the player we are using https://www.dropbox.com/s/xmokrmpuxu99rcs/QueryImage.png?dl=0
> 
> Do you have any suggestion?

I think this page is well designed.
