### ISSUE TITLE
如果裁剪的VIDEO_MAX_TIME不是10的话页面上存在一个显示bug

### ISSUE THREAD

**Issue by Noah1991** [iknow4/Android-Video-Trimmer#59]
等VIDEO_MAX_TIME不等于10的时候，裁剪时，底部seekbar所显示的视频时长不正确。

**Comment by Noah1991** [comment]
将MAX_COUNT_RANGE设置为VIDEO_MAX_TIME后，可以规避这个问题，但是出现个新问题，seekbar显示的时长比真实时长差1秒。
还有就是以上问题我是用30秒以上的视频测试的

**Comment by Noah1991** [comment]
将
public static final int THUMB_WIDTH = (SCREEN_WIDTH_FULL - RECYCLER_VIEW_PADDING * 2) / VIDEO_MAX_TIME;
改为
public static final int THUMB_WIDTH = (SCREEN_WIDTH_FULL - RECYCLER_VIEW_PADDING * 2) / MAX_COUNT_RANGE;
后正常了

**Comment by cuk2dn95** [comment]
@Noah1991  thanks, 
for everyone wants to change VIDEO_MAX_TIME
just change `public static final int THUMB_WIDTH = (SCREEN_WIDTH_FULL - RECYCLER_VIEW_PADDING * 2) / MAX_COUNT_RANGE;`
