### ISSUE TITLE
Unable to compile this project in android studio

### ISSUE THREAD

**Issue by nerviantone** [iknow4/Android-Video-Trimmer#61]
I imported this and was not able to compile it . It's giving an error like cannot find symbol method releaseCamera() in line 86 mSurfaceView.releaseCamera(); inside the file VideoSelectActivity.java. Can somebody check if they get the same error ?

**Comment by iknow4** [comment]
> I imported this and was not able to compile it . It's giving an error like cannot find symbol method releaseCamera() in line 86 mSurfaceView.releaseCamera(); inside the file VideoSelectActivity.java. Can somebody check if they get the same error ?

will fix it soon, thank you for feedback 🙏 @nerviantone

**Comment by iknow4** [comment]
Already fixed it @nerviantone
